### ISSUE TITLE
[linux] nonfatal error when doing 'brew info x'

### ISSUE THREAD

**Issue by casallas** [casallas/homebrew#20]
It stills shows the formula information but shows an annoying message, e.g. with vrjuggler:

``` sh
$ brew info vrjuggler
vrjuggler 3.0.0-1
http://code.google.com/p/vrjuggler/
Depends on: boost, cppdom, gmtl, flagpoll, freealut, vrpn, omniorb
Not installed
Error: undefined method `basename' for "/home/users/casallas/homebrew/Library/Formula/vrjuggler.rb":String
Please follow the instructions to report this bug at: 
https://github.com/rubiojr/homebrew/wiki/new-issue
/home/users/casallas/homebrew/Library/Homebrew/brew.h.rb:204:in `github_info'
/home/users/casallas/homebrew/Library/Homebrew/brew.h.rb:246:in `info'
/home/users/casallas/homebrew/bin/brew:258:in `block in <main>'
/home/users/casallas/homebrew/bin/brew:258:in `each'
/home/users/casallas/homebrew/bin/brew:258:in `<main>'
```

**Comment by casallas** [comment]
This was caused by ab29fc5, but has been solved by reverting in 327ac26def10ceeec298982a6d3f38c9ca75ca39
